baseURL = 'https://bdk44.github.io/'
languageCode = 'ru-ru'
title = '.bdk writeups'
theme = 'PaperMod'

[params]
    env = "production"
    title = ".bdk writeups"
    description = "Райтапы"
    defaultTheme = "dark" # По умолчанию всегда будет включаться темная тема
    disableSpecial1stPost = true
    
    # Меню навигации
    [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
    
    [[menu.main]]
    name = "Райтапы"
    url = "/categories/writeups/"
    weight = 2

    [[menu.main]]
    name = "Заметки"
    url = "/categories/notes/"
    weight = 3

    [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true # Включает нумерацию строк в блоках с кодом
    style = "monokai" # Стиль подсветки синтаксиса